name: Vercel Deployment Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: Vercel - brick-and-brain-website: lint
          token: ${{ secrets.VERCEL_TOKEN }}
